wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.19.9
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744221502
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 14
      - 23
      - 37
      4: 3.9.16
      5: 0.19.9
      8:
      - 5
      13: darwin-arm64
colsample_bytree:
  desc: null
  value: 0.75
learning_rate:
  desc: null
  value: 0.2
max_depth:
  desc: null
  value: 6
min_child_weight:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 100
subsample:
  desc: null
  value: 1
